#compdef gen_completion.py

# AUTOMATICALLY GENERATED by `shtab`


_shtab_gen_completion_py_commands() {
  local _commands=(
    "a:"
    "audit:"
    "b:"
    "batch:"
    "c:"
    "check:"
    "convert:"
    "d:"
    "diff:"
    "download:"
    "extract:"
    "i:"
    "inspect:"
    "mirror:"
    "p:"
    "preview:"
    "r:"
    "report:"
    "risk:"
    "s:"
    "scan:"
    "search:"
    "setup:"
    "stats:"
    "ui:"
    "um:"
    "update-manifest:"
    "verify:"
    "x:"
  )
  _describe 'gen_completion.py commands' _commands
}

_shtab_gen_completion_py_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-v,--verbose}"[Enable verbose logging (DEBUG level)]"
  {-q,--quiet}"[Enable quiet mode (ERROR level only, no progress bars)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_defaults_added=0

_shtab_gen_completion_py_a_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_a_defaults_added=0

_shtab_gen_completion_py_audit_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_audit_defaults_added=0

_shtab_gen_completion_py_b_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Directory to save the downloaded extensions (default\: .)]:output_dir:"
  {-w,--workers}"[Number of parallel workers (default\: 4)]:workers:"
  ":Path to the batch file containing URLs:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_b_defaults_added=0

_shtab_gen_completion_py_batch_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Directory to save the downloaded extensions (default\: .)]:output_dir:"
  {-w,--workers}"[Number of parallel workers (default\: 4)]:workers:"
  ":Path to the batch file containing URLs:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_batch_defaults_added=0

_shtab_gen_completion_py_c_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_c_defaults_added=0

_shtab_gen_completion_py_check_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_check_defaults_added=0

_shtab_gen_completion_py_convert_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--to[Target format (default\: zip)]:to:(zip)"
  {-o,--output}"[Output file path]:output:"
  ":Input file or directory:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_convert_defaults_added=0

_shtab_gen_completion_py_d_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Directory to save the downloaded extension (default\: .)]:output_dir:"
  {-m,--save-metadata}"[Save metadata to a JSON file alongside the extension]"
  {-x,--extract}"[Automatically extract the extension to a folder]"
  ":The browser type (chrome\/c, edge\/e, firefox\/f):(chrome c edge e firefox f)"
  ":The URL of the extension in the Web Store:"
  ":The browser type (chrome\/c, edge\/e, firefox\/f):(chrome c edge e firefox f)"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_d_defaults_added=0

_shtab_gen_completion_py_diff_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the old .crx or .xpi file:"
  ":Path to the new .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_diff_defaults_added=0

_shtab_gen_completion_py_download_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Directory to save the downloaded extension (default\: .)]:output_dir:"
  {-m,--save-metadata}"[Save metadata to a JSON file alongside the extension]"
  {-x,--extract}"[Automatically extract the extension to a folder]"
  ":The browser type (chrome\/c, edge\/e, firefox\/f):(chrome c edge e firefox f)"
  ":The URL of the extension in the Web Store:"
  ":The browser type (chrome\/c, edge\/e, firefox\/f):(chrome c edge e firefox f)"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_download_defaults_added=0

_shtab_gen_completion_py_extract_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Directory to extract to (default\: \<filename_stem\> in current dir)]:output_dir:"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_extract_defaults_added=0

_shtab_gen_completion_py_i_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_i_defaults_added=0

_shtab_gen_completion_py_inspect_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_inspect_defaults_added=0

_shtab_gen_completion_py_mirror_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Target directory (default\: .)]:output_dir:"
  "--prune[Remove files not in the list]"
  {-w,--workers}"[Number of parallel workers (default\: 4)]:workers:"
  ":Path to the list file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_mirror_defaults_added=0

_shtab_gen_completion_py_p_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_p_defaults_added=0

_shtab_gen_completion_py_preview_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_preview_defaults_added=0

_shtab_gen_completion_py_r_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_r_defaults_added=0

_shtab_gen_completion_py_report_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output}"[Output file path (default\: \<filename\>_REPORT.md)]:output:"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_report_defaults_added=0

_shtab_gen_completion_py_risk_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_risk_defaults_added=0

_shtab_gen_completion_py_s_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  "--csv[Output results as CSV]"
  ":The browser type (only firefox\/f supported for search):(firefox f)"
  ":The search query:"
  ":The browser type (only firefox\/f supported for search):(firefox f)"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_s_defaults_added=0

_shtab_gen_completion_py_scan_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  "--csv[Output results as CSV]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_scan_defaults_added=0

_shtab_gen_completion_py_search_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  "--csv[Output results as CSV]"
  ":The browser type (only firefox\/f supported for search):(firefox f)"
  ":The search query:"
  ":The browser type (only firefox\/f supported for search):(firefox f)"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_search_defaults_added=0

_shtab_gen_completion_py_setup_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_setup_defaults_added=0

_shtab_gen_completion_py_stats_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Directory to scan (default\: current directory):"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_stats_defaults_added=0

_shtab_gen_completion_py_ui_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_ui_defaults_added=0

_shtab_gen_completion_py_um_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--base-url[Base URL where extensions are hosted]:base_url:"
  "--output[Output file path (optional)]:output:"
  ":Directory containing extension files:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_um_defaults_added=0

_shtab_gen_completion_py_update_manifest_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--base-url[Base URL where extensions are hosted]:base_url:"
  "--output[Output file path (optional)]:output:"
  ":Directory containing extension files:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_update_manifest_defaults_added=0

_shtab_gen_completion_py_verify_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_verify_defaults_added=0

_shtab_gen_completion_py_x_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Directory to extract to (default\: \<filename_stem\> in current dir)]:output_dir:"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_x_defaults_added=0


_shtab_gen_completion_py() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->gen_completion.py'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_gen_completion_py_defaults_added )); then
    if (( ${_shtab_gen_completion_py_options[(I)${(q)one_or_more}*]} +          ${_shtab_gen_completion_py_options[(I)${(q)remainder}*]} +          ${_shtab_gen_completion_py_options[(I)${(q)default}]} == 0 )); then
      _shtab_gen_completion_py_options+=(': :_shtab_gen_completion_py_commands' '*::: :->gen_completion.py')
    fi
    _shtab_gen_completion_py_defaults_added=1
  fi
  _arguments -C -s $_shtab_gen_completion_py_options

  case $state in
    gen_completion.py)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_gen_completion_py-$line[1]:"
      case $line[1] in
        a) _arguments -C -s $_shtab_gen_completion_py_a_options ;;
        audit) _arguments -C -s $_shtab_gen_completion_py_audit_options ;;
        b) _arguments -C -s $_shtab_gen_completion_py_b_options ;;
        batch) _arguments -C -s $_shtab_gen_completion_py_batch_options ;;
        c) _arguments -C -s $_shtab_gen_completion_py_c_options ;;
        check) _arguments -C -s $_shtab_gen_completion_py_check_options ;;
        convert) _arguments -C -s $_shtab_gen_completion_py_convert_options ;;
        d) _arguments -C -s $_shtab_gen_completion_py_d_options ;;
        diff) _arguments -C -s $_shtab_gen_completion_py_diff_options ;;
        download) _arguments -C -s $_shtab_gen_completion_py_download_options ;;
        extract) _arguments -C -s $_shtab_gen_completion_py_extract_options ;;
        i) _arguments -C -s $_shtab_gen_completion_py_i_options ;;
        inspect) _arguments -C -s $_shtab_gen_completion_py_inspect_options ;;
        mirror) _arguments -C -s $_shtab_gen_completion_py_mirror_options ;;
        p) _arguments -C -s $_shtab_gen_completion_py_p_options ;;
        preview) _arguments -C -s $_shtab_gen_completion_py_preview_options ;;
        r) _arguments -C -s $_shtab_gen_completion_py_r_options ;;
        report) _arguments -C -s $_shtab_gen_completion_py_report_options ;;
        risk) _arguments -C -s $_shtab_gen_completion_py_risk_options ;;
        s) _arguments -C -s $_shtab_gen_completion_py_s_options ;;
        scan) _arguments -C -s $_shtab_gen_completion_py_scan_options ;;
        search) _arguments -C -s $_shtab_gen_completion_py_search_options ;;
        setup) _arguments -C -s $_shtab_gen_completion_py_setup_options ;;
        stats) _arguments -C -s $_shtab_gen_completion_py_stats_options ;;
        ui) _arguments -C -s $_shtab_gen_completion_py_ui_options ;;
        um) _arguments -C -s $_shtab_gen_completion_py_um_options ;;
        update-manifest) _arguments -C -s $_shtab_gen_completion_py_update_manifest_options ;;
        verify) _arguments -C -s $_shtab_gen_completion_py_verify_options ;;
        x) _arguments -C -s $_shtab_gen_completion_py_x_options ;;
      esac
  esac
}



typeset -A opt_args

if [[ $zsh_eval_context[-1] == eval ]]; then
  # eval/source/. command, register function for later
  compdef _shtab_gen_completion_py -N gen_completion.py
else
  # autoload from fpath, call function directly
  _shtab_gen_completion_py "$@"
fi
