# AUTOMATICALLY GENERATED by `shtab`

_shtab_gen_completion_py_subparsers=('download' 'd' 'search' 's' 'inspect' 'i' 'extract' 'x' 'check' 'c' 'preview' 'p' 'audit' 'a' 'diff' 'risk' 'r' 'verify' 'scan' 'report' 'update-manifest' 'um' 'mirror' 'batch' 'b' 'ui' 'setup' 'convert' 'stats')

_shtab_gen_completion_py_option_strings=('-h' '--help' '-v' '--verbose' '-q' '--quiet')
_shtab_gen_completion_py_download_option_strings=('-h' '--help' '-o' '--output-dir' '-m' '--save-metadata' '-x' '--extract')
_shtab_gen_completion_py_d_option_strings=('-h' '--help' '-o' '--output-dir' '-m' '--save-metadata' '-x' '--extract')
_shtab_gen_completion_py_search_option_strings=('-h' '--help' '--json' '--csv')
_shtab_gen_completion_py_s_option_strings=('-h' '--help' '--json' '--csv')
_shtab_gen_completion_py_inspect_option_strings=('-h' '--help' '--json')
_shtab_gen_completion_py_i_option_strings=('-h' '--help' '--json')
_shtab_gen_completion_py_extract_option_strings=('-h' '--help' '-o' '--output-dir')
_shtab_gen_completion_py_x_option_strings=('-h' '--help' '-o' '--output-dir')
_shtab_gen_completion_py_check_option_strings=('-h' '--help' '--json')
_shtab_gen_completion_py_c_option_strings=('-h' '--help' '--json')
_shtab_gen_completion_py_preview_option_strings=('-h' '--help')
_shtab_gen_completion_py_p_option_strings=('-h' '--help')
_shtab_gen_completion_py_audit_option_strings=('-h' '--help' '--json')
_shtab_gen_completion_py_a_option_strings=('-h' '--help' '--json')
_shtab_gen_completion_py_diff_option_strings=('-h' '--help' '--json')
_shtab_gen_completion_py_risk_option_strings=('-h' '--help' '--json')
_shtab_gen_completion_py_r_option_strings=('-h' '--help' '--json')
_shtab_gen_completion_py_verify_option_strings=('-h' '--help' '--json')
_shtab_gen_completion_py_scan_option_strings=('-h' '--help' '--json' '--csv')
_shtab_gen_completion_py_report_option_strings=('-h' '--help' '-o' '--output')
_shtab_gen_completion_py_update_manifest_option_strings=('-h' '--help' '--base-url' '--output')
_shtab_gen_completion_py_um_option_strings=('-h' '--help' '--base-url' '--output')
_shtab_gen_completion_py_mirror_option_strings=('-h' '--help' '-o' '--output-dir' '--prune' '-w' '--workers')
_shtab_gen_completion_py_batch_option_strings=('-h' '--help' '-o' '--output-dir' '-w' '--workers')
_shtab_gen_completion_py_b_option_strings=('-h' '--help' '-o' '--output-dir' '-w' '--workers')
_shtab_gen_completion_py_ui_option_strings=('-h' '--help')
_shtab_gen_completion_py_setup_option_strings=('-h' '--help')
_shtab_gen_completion_py_convert_option_strings=('-h' '--help' '--to' '-o' '--output')
_shtab_gen_completion_py_stats_option_strings=('-h' '--help' '--json')



_shtab_gen_completion_py_pos_0_choices=('download' 'd' 'search' 's' 'inspect' 'i' 'extract' 'x' 'check' 'c' 'preview' 'p' 'audit' 'a' 'diff' 'risk' 'r' 'verify' 'scan' 'report' 'update-manifest' 'um' 'mirror' 'batch' 'b' 'ui' 'setup' 'convert' 'stats')
_shtab_gen_completion_py_download_pos_0_choices=('chrome' 'c' 'edge' 'e' 'firefox' 'f')
_shtab_gen_completion_py_d_pos_0_choices=('chrome' 'c' 'edge' 'e' 'firefox' 'f')
_shtab_gen_completion_py_search_pos_0_choices=('firefox' 'f')
_shtab_gen_completion_py_s_pos_0_choices=('firefox' 'f')
_shtab_gen_completion_py_convert___to_choices=('zip')

_shtab_gen_completion_py_pos_0_nargs=A...
_shtab_gen_completion_py__h_nargs=0
_shtab_gen_completion_py___help_nargs=0
_shtab_gen_completion_py__v_nargs=0
_shtab_gen_completion_py___verbose_nargs=0
_shtab_gen_completion_py__q_nargs=0
_shtab_gen_completion_py___quiet_nargs=0
_shtab_gen_completion_py_download__h_nargs=0
_shtab_gen_completion_py_download___help_nargs=0
_shtab_gen_completion_py_download__m_nargs=0
_shtab_gen_completion_py_download___save_metadata_nargs=0
_shtab_gen_completion_py_download__x_nargs=0
_shtab_gen_completion_py_download___extract_nargs=0
_shtab_gen_completion_py_d__h_nargs=0
_shtab_gen_completion_py_d___help_nargs=0
_shtab_gen_completion_py_d__m_nargs=0
_shtab_gen_completion_py_d___save_metadata_nargs=0
_shtab_gen_completion_py_d__x_nargs=0
_shtab_gen_completion_py_d___extract_nargs=0
_shtab_gen_completion_py_search__h_nargs=0
_shtab_gen_completion_py_search___help_nargs=0
_shtab_gen_completion_py_search___json_nargs=0
_shtab_gen_completion_py_search___csv_nargs=0
_shtab_gen_completion_py_s__h_nargs=0
_shtab_gen_completion_py_s___help_nargs=0
_shtab_gen_completion_py_s___json_nargs=0
_shtab_gen_completion_py_s___csv_nargs=0
_shtab_gen_completion_py_inspect__h_nargs=0
_shtab_gen_completion_py_inspect___help_nargs=0
_shtab_gen_completion_py_inspect___json_nargs=0
_shtab_gen_completion_py_i__h_nargs=0
_shtab_gen_completion_py_i___help_nargs=0
_shtab_gen_completion_py_i___json_nargs=0
_shtab_gen_completion_py_extract__h_nargs=0
_shtab_gen_completion_py_extract___help_nargs=0
_shtab_gen_completion_py_x__h_nargs=0
_shtab_gen_completion_py_x___help_nargs=0
_shtab_gen_completion_py_check__h_nargs=0
_shtab_gen_completion_py_check___help_nargs=0
_shtab_gen_completion_py_check___json_nargs=0
_shtab_gen_completion_py_c__h_nargs=0
_shtab_gen_completion_py_c___help_nargs=0
_shtab_gen_completion_py_c___json_nargs=0
_shtab_gen_completion_py_preview__h_nargs=0
_shtab_gen_completion_py_preview___help_nargs=0
_shtab_gen_completion_py_p__h_nargs=0
_shtab_gen_completion_py_p___help_nargs=0
_shtab_gen_completion_py_audit__h_nargs=0
_shtab_gen_completion_py_audit___help_nargs=0
_shtab_gen_completion_py_audit___json_nargs=0
_shtab_gen_completion_py_a__h_nargs=0
_shtab_gen_completion_py_a___help_nargs=0
_shtab_gen_completion_py_a___json_nargs=0
_shtab_gen_completion_py_diff__h_nargs=0
_shtab_gen_completion_py_diff___help_nargs=0
_shtab_gen_completion_py_diff___json_nargs=0
_shtab_gen_completion_py_risk__h_nargs=0
_shtab_gen_completion_py_risk___help_nargs=0
_shtab_gen_completion_py_risk___json_nargs=0
_shtab_gen_completion_py_r__h_nargs=0
_shtab_gen_completion_py_r___help_nargs=0
_shtab_gen_completion_py_r___json_nargs=0
_shtab_gen_completion_py_verify__h_nargs=0
_shtab_gen_completion_py_verify___help_nargs=0
_shtab_gen_completion_py_verify___json_nargs=0
_shtab_gen_completion_py_scan__h_nargs=0
_shtab_gen_completion_py_scan___help_nargs=0
_shtab_gen_completion_py_scan___json_nargs=0
_shtab_gen_completion_py_scan___csv_nargs=0
_shtab_gen_completion_py_report__h_nargs=0
_shtab_gen_completion_py_report___help_nargs=0
_shtab_gen_completion_py_update_manifest__h_nargs=0
_shtab_gen_completion_py_update_manifest___help_nargs=0
_shtab_gen_completion_py_um__h_nargs=0
_shtab_gen_completion_py_um___help_nargs=0
_shtab_gen_completion_py_mirror__h_nargs=0
_shtab_gen_completion_py_mirror___help_nargs=0
_shtab_gen_completion_py_mirror___prune_nargs=0
_shtab_gen_completion_py_batch__h_nargs=0
_shtab_gen_completion_py_batch___help_nargs=0
_shtab_gen_completion_py_b__h_nargs=0
_shtab_gen_completion_py_b___help_nargs=0
_shtab_gen_completion_py_ui__h_nargs=0
_shtab_gen_completion_py_ui___help_nargs=0
_shtab_gen_completion_py_setup__h_nargs=0
_shtab_gen_completion_py_setup___help_nargs=0
_shtab_gen_completion_py_convert__h_nargs=0
_shtab_gen_completion_py_convert___help_nargs=0
_shtab_gen_completion_py_stats__h_nargs=0
_shtab_gen_completion_py_stats___help_nargs=0
_shtab_gen_completion_py_stats___json_nargs=0


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_gen_completion_py() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local previous_word="${COMP_WORDS[COMP_CWORD-1]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_gen_completion_py
  local word_index=0
  local pos_only=0 # "--" delimeter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != "?" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_${completed_positional_actions}" true
      fi
    else
      pos_only=1 # "--" delimeter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  if [[ $pos_only = 0 && "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    COMPREPLY=( $(compgen -W "${current_option_strings[*]}" -- "${completing_word}") )
  elif [[ "${previous_word}" == ">" || "${previous_word}" == ">>" ||
          "${previous_word}" =~ ^[12]">" || "${previous_word}" =~ ^[12]">>" ]]; then
    # handle redirection operators
    COMPREPLY=( $(compgen -f -- "${completing_word}") )
  else
    # use choices & compgen
    local IFS=$'\n' # items may contain spaces, so delimit using newline
    COMPREPLY=( $([ -n "${current_action_compgen}" ] \
                  && "${current_action_compgen}" "${completing_word}") )
    unset IFS
    COMPREPLY+=( $(compgen -W "${current_action_choices[*]}" -- "${completing_word}") )
  fi

  return 0
}

complete -o filenames -F _shtab_gen_completion_py gen_completion.py