#compdef gen_completion.py

# AUTOMATICALLY GENERATED by `shtab`


_shtab_gen_completion_py_commands() {
  local _commands=(
    "a:"
    "analyze:"
    "audit:"
    "b:"
    "batch:"
    "clean:"
    "config:"
    "convert:"
    "d:"
    "diff:"
    "download:"
    "explain:"
    "extract:"
    "graph:"
    "history:"
    "i:"
    "info:"
    "inspect:"
    "locales:"
    "mirror:"
    "optimize:"
    "p:"
    "plugin:"
    "preview:"
    "r:"
    "report:"
    "risk:"
    "s:"
    "scan:"
    "schema:"
    "search:"
    "serve:"
    "setup:"
    "stats:"
    "timeline:"
    "tutorial:"
    "ui:"
    "um:"
    "update-manifest:"
    "verify:"
    "x:"
  )
  _describe 'gen_completion.py commands' _commands
}

_shtab_gen_completion_py_config_commands() {
  local _commands=(
    "init:"
    "show:"
  )
  _describe 'gen_completion.py config commands' _commands
}

_shtab_gen_completion_py_plugin_commands() {
  local _commands=(
    "disable:"
    "enable:"
    "install:"
    "list:"
    "remove:"
  )
  _describe 'gen_completion.py plugin commands' _commands
}

_shtab_gen_completion_py_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "(- : *)--version[show program\'s version number and exit]"
  {-v,--verbose}"[Enable verbose logging (DEBUG level)]"
  {-q,--quiet}"[Enable quiet mode (ERROR level only, no progress bars)]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_defaults_added=0

_shtab_gen_completion_py_a_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_a_defaults_added=0

_shtab_gen_completion_py_analyze_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--complexity[Calculate cyclomatic complexity of JS files]"
  "--entropy[Calculate entropy of files to detect obfuscation\/packing]"
  "--domains[Extract domains and URLs from source code]"
  "--secrets[Scan for potential secrets (API keys, tokens)]"
  "--yara[Path to YARA rules file or directory to scan against]:yara:"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_analyze_defaults_added=0

_shtab_gen_completion_py_audit_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_audit_defaults_added=0

_shtab_gen_completion_py_b_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Directory to save the downloaded extensions (default\: .)]:output_dir:"
  {-w,--workers}"[Number of parallel workers (default\: 4)]:workers:"
  ":Path to the batch file containing URLs:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_b_defaults_added=0

_shtab_gen_completion_py_batch_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Directory to save the downloaded extensions (default\: .)]:output_dir:"
  {-w,--workers}"[Number of parallel workers (default\: 4)]:workers:"
  ":Path to the batch file containing URLs:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_batch_defaults_added=0

_shtab_gen_completion_py_clean_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--cache[Clean build and test caches (default)]"
  "--downloads[Clean download directory]"
  "--all[Clean everything]"
  "--dry-run[Show what would be deleted without deleting]"
  {-f,--force}"[Skip confirmation]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_clean_defaults_added=0

_shtab_gen_completion_py_config_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_config_defaults_added=0

_shtab_gen_completion_py_config_init_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-f,--force}"[Overwrite existing configuration]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_config_init_defaults_added=0

_shtab_gen_completion_py_config_show_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_config_show_defaults_added=0

_shtab_gen_completion_py_convert_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--to[Target format (default\: zip)]:to:(zip)"
  {-o,--output}"[Output file path]:output:"
  ":Input file or directory:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_convert_defaults_added=0

_shtab_gen_completion_py_d_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Directory to save the downloaded extension (default\: .)]:output_dir:"
  {-m,--save-metadata}"[Save metadata to a JSON file alongside the extension]"
  {-x,--extract}"[Automatically extract the extension to a folder]"
  "--verify-hash[Verify the downloaded file against this SHA256 hash]:verify_hash:"
  ":The browser type (chrome\/c, edge\/e, firefox\/f):(chrome c edge e firefox f)"
  ":The URL of the extension in the Web Store:"
  ":The browser type (chrome\/c, edge\/e, firefox\/f):(chrome c edge e firefox f)"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_d_defaults_added=0

_shtab_gen_completion_py_diff_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the old .crx or .xpi file:"
  ":Path to the new .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_diff_defaults_added=0

_shtab_gen_completion_py_download_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Directory to save the downloaded extension (default\: .)]:output_dir:"
  {-m,--save-metadata}"[Save metadata to a JSON file alongside the extension]"
  {-x,--extract}"[Automatically extract the extension to a folder]"
  "--verify-hash[Verify the downloaded file against this SHA256 hash]:verify_hash:"
  ":The browser type (chrome\/c, edge\/e, firefox\/f):(chrome c edge e firefox f)"
  ":The URL of the extension in the Web Store:"
  ":The browser type (chrome\/c, edge\/e, firefox\/f):(chrome c edge e firefox f)"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_download_defaults_added=0

_shtab_gen_completion_py_explain_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":The permission string to explain:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_explain_defaults_added=0

_shtab_gen_completion_py_extract_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Output directory (default\: \<filename\>_extracted)]:output_dir:"
  ":Path to extension file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_extract_defaults_added=0

_shtab_gen_completion_py_graph_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output}"[Output file path (default\: \<filename\>_graph.html)]:output:"
  ":Path to extension file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_graph_defaults_added=0

_shtab_gen_completion_py_history_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--limit[Number of entries to show (default\: 20)]:limit:"
  "--clear[Clear the history]"
  "--json[Output results as JSON]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_history_defaults_added=0

_shtab_gen_completion_py_i_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_i_defaults_added=0

_shtab_gen_completion_py_info_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output as JSON]"
  ":Path to extension file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_info_defaults_added=0

_shtab_gen_completion_py_inspect_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_inspect_defaults_added=0

_shtab_gen_completion_py_locales_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_locales_defaults_added=0

_shtab_gen_completion_py_mirror_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Target directory (default\: .)]:output_dir:"
  "--prune[Remove files not in the list]"
  {-w,--workers}"[Number of parallel workers (default\: 4)]:workers:"
  ":Path to the list file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_mirror_defaults_added=0

_shtab_gen_completion_py_optimize_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-q,--quality}"[Image quality (1-100, default\: 85)]:quality:"
  "--json[Output results as JSON]"
  ":Path to the extension directory:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_optimize_defaults_added=0

_shtab_gen_completion_py_p_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_p_defaults_added=0

_shtab_gen_completion_py_plugin_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_plugin_defaults_added=0

_shtab_gen_completion_py_plugin_disable_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Plugin name:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_plugin_disable_defaults_added=0

_shtab_gen_completion_py_plugin_enable_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Plugin name:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_plugin_enable_defaults_added=0

_shtab_gen_completion_py_plugin_install_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Path to plugin file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_plugin_install_defaults_added=0

_shtab_gen_completion_py_plugin_list_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_plugin_list_defaults_added=0

_shtab_gen_completion_py_plugin_remove_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Plugin name:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_plugin_remove_defaults_added=0

_shtab_gen_completion_py_preview_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_preview_defaults_added=0

_shtab_gen_completion_py_r_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_r_defaults_added=0

_shtab_gen_completion_py_report_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output}"[Output file path (default\: \<filename\>_REPORT.md for markdown, stdout for JSON)]:output:"
  "--json[Output unified report as JSON]"
  "--yara[Path to YARA rules file or directory (optional, for JSON report)]:yara:"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_report_defaults_added=0

_shtab_gen_completion_py_risk_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_risk_defaults_added=0

_shtab_gen_completion_py_s_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  "--csv[Output results as CSV]"
  ":The browser type (only firefox\/f supported for search):(firefox f)"
  ":The search query:"
  ":The browser type (only firefox\/f supported for search):(firefox f)"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_s_defaults_added=0

_shtab_gen_completion_py_scan_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  "--csv[Output results as CSV]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_scan_defaults_added=0

_shtab_gen_completion_py_schema_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":The type of schema to generate:(config audit risk history scan)"
  ":The type of schema to generate:(config audit risk history scan)"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_schema_defaults_added=0

_shtab_gen_completion_py_search_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  "--csv[Output results as CSV]"
  ":The browser type (only firefox\/f supported for search):(firefox f)"
  ":The search query:"
  ":The browser type (only firefox\/f supported for search):(firefox f)"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_search_defaults_added=0

_shtab_gen_completion_py_serve_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-d,--directory}"[Directory to serve (default\: current directory)]:directory:"
  "--host[Host to bind to (default\: 127.0.0.1)]:host:"
  {-p,--port}"[Port to listen on (default\: 8000)]:port:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_serve_defaults_added=0

_shtab_gen_completion_py_setup_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_setup_defaults_added=0

_shtab_gen_completion_py_stats_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Directory to scan (default\: current directory):"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_stats_defaults_added=0

_shtab_gen_completion_py_timeline_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx or .xpi file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_timeline_defaults_added=0

_shtab_gen_completion_py_tutorial_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_tutorial_defaults_added=0

_shtab_gen_completion_py_ui_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_ui_defaults_added=0

_shtab_gen_completion_py_um_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--base-url[Base URL where extensions are hosted]:base_url:"
  "--output[Output file path (optional)]:output:"
  ":Directory containing extension files:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_um_defaults_added=0

_shtab_gen_completion_py_update_manifest_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--base-url[Base URL where extensions are hosted]:base_url:"
  "--output[Output file path (optional)]:output:"
  ":Directory containing extension files:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_update_manifest_defaults_added=0

_shtab_gen_completion_py_verify_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[Output results as JSON]"
  ":Path to the .crx file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_verify_defaults_added=0

_shtab_gen_completion_py_x_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  {-o,--output-dir}"[Output directory (default\: \<filename\>_extracted)]:output_dir:"
  ":Path to extension file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_gen_completion_py_x_defaults_added=0


_shtab_gen_completion_py() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->gen_completion.py'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_gen_completion_py_defaults_added )); then
    if (( ${_shtab_gen_completion_py_options[(I)${(q)one_or_more}*]} +          ${_shtab_gen_completion_py_options[(I)${(q)remainder}*]} +          ${_shtab_gen_completion_py_options[(I)${(q)default}]} == 0 )); then
      _shtab_gen_completion_py_options+=(': :_shtab_gen_completion_py_commands' '*::: :->gen_completion.py')
    fi
    _shtab_gen_completion_py_defaults_added=1
  fi
  _arguments -C -s $_shtab_gen_completion_py_options

  case $state in
    gen_completion.py)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_gen_completion_py-$line[1]:"
      case $line[1] in
        a) _arguments -C -s $_shtab_gen_completion_py_a_options ;;
        analyze) _arguments -C -s $_shtab_gen_completion_py_analyze_options ;;
        audit) _arguments -C -s $_shtab_gen_completion_py_audit_options ;;
        b) _arguments -C -s $_shtab_gen_completion_py_b_options ;;
        batch) _arguments -C -s $_shtab_gen_completion_py_batch_options ;;
        clean) _arguments -C -s $_shtab_gen_completion_py_clean_options ;;
        config) _shtab_gen_completion_py_config ;;
        convert) _arguments -C -s $_shtab_gen_completion_py_convert_options ;;
        d) _arguments -C -s $_shtab_gen_completion_py_d_options ;;
        diff) _arguments -C -s $_shtab_gen_completion_py_diff_options ;;
        download) _arguments -C -s $_shtab_gen_completion_py_download_options ;;
        explain) _arguments -C -s $_shtab_gen_completion_py_explain_options ;;
        extract) _arguments -C -s $_shtab_gen_completion_py_extract_options ;;
        graph) _arguments -C -s $_shtab_gen_completion_py_graph_options ;;
        history) _arguments -C -s $_shtab_gen_completion_py_history_options ;;
        i) _arguments -C -s $_shtab_gen_completion_py_i_options ;;
        info) _arguments -C -s $_shtab_gen_completion_py_info_options ;;
        inspect) _arguments -C -s $_shtab_gen_completion_py_inspect_options ;;
        locales) _arguments -C -s $_shtab_gen_completion_py_locales_options ;;
        mirror) _arguments -C -s $_shtab_gen_completion_py_mirror_options ;;
        optimize) _arguments -C -s $_shtab_gen_completion_py_optimize_options ;;
        p) _arguments -C -s $_shtab_gen_completion_py_p_options ;;
        plugin) _shtab_gen_completion_py_plugin ;;
        preview) _arguments -C -s $_shtab_gen_completion_py_preview_options ;;
        r) _arguments -C -s $_shtab_gen_completion_py_r_options ;;
        report) _arguments -C -s $_shtab_gen_completion_py_report_options ;;
        risk) _arguments -C -s $_shtab_gen_completion_py_risk_options ;;
        s) _arguments -C -s $_shtab_gen_completion_py_s_options ;;
        scan) _arguments -C -s $_shtab_gen_completion_py_scan_options ;;
        schema) _arguments -C -s $_shtab_gen_completion_py_schema_options ;;
        search) _arguments -C -s $_shtab_gen_completion_py_search_options ;;
        serve) _arguments -C -s $_shtab_gen_completion_py_serve_options ;;
        setup) _arguments -C -s $_shtab_gen_completion_py_setup_options ;;
        stats) _arguments -C -s $_shtab_gen_completion_py_stats_options ;;
        timeline) _arguments -C -s $_shtab_gen_completion_py_timeline_options ;;
        tutorial) _arguments -C -s $_shtab_gen_completion_py_tutorial_options ;;
        ui) _arguments -C -s $_shtab_gen_completion_py_ui_options ;;
        um) _arguments -C -s $_shtab_gen_completion_py_um_options ;;
        update-manifest) _arguments -C -s $_shtab_gen_completion_py_update_manifest_options ;;
        verify) _arguments -C -s $_shtab_gen_completion_py_verify_options ;;
        x) _arguments -C -s $_shtab_gen_completion_py_x_options ;;
      esac
  esac
}

_shtab_gen_completion_py_config() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->config'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_gen_completion_py_config_defaults_added )); then
    if (( ${_shtab_gen_completion_py_config_options[(I)${(q)one_or_more}*]} +          ${_shtab_gen_completion_py_config_options[(I)${(q)remainder}*]} +          ${_shtab_gen_completion_py_config_options[(I)${(q)default}]} == 0 )); then
      _shtab_gen_completion_py_config_options+=(': :_shtab_gen_completion_py_config_commands' '*::: :->config')
    fi
    _shtab_gen_completion_py_config_defaults_added=1
  fi
  _arguments -C -s $_shtab_gen_completion_py_config_options

  case $state in
    config)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_gen_completion_py_config-$line[1]:"
      case $line[1] in
        init) _arguments -C -s $_shtab_gen_completion_py_config_init_options ;;
        show) _arguments -C -s $_shtab_gen_completion_py_config_show_options ;;
      esac
  esac
}

_shtab_gen_completion_py_plugin() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->plugin'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_gen_completion_py_plugin_defaults_added )); then
    if (( ${_shtab_gen_completion_py_plugin_options[(I)${(q)one_or_more}*]} +          ${_shtab_gen_completion_py_plugin_options[(I)${(q)remainder}*]} +          ${_shtab_gen_completion_py_plugin_options[(I)${(q)default}]} == 0 )); then
      _shtab_gen_completion_py_plugin_options+=(': :_shtab_gen_completion_py_plugin_commands' '*::: :->plugin')
    fi
    _shtab_gen_completion_py_plugin_defaults_added=1
  fi
  _arguments -C -s $_shtab_gen_completion_py_plugin_options

  case $state in
    plugin)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_gen_completion_py_plugin-$line[1]:"
      case $line[1] in
        disable) _arguments -C -s $_shtab_gen_completion_py_plugin_disable_options ;;
        enable) _arguments -C -s $_shtab_gen_completion_py_plugin_enable_options ;;
        install) _arguments -C -s $_shtab_gen_completion_py_plugin_install_options ;;
        list) _arguments -C -s $_shtab_gen_completion_py_plugin_list_options ;;
        remove) _arguments -C -s $_shtab_gen_completion_py_plugin_remove_options ;;
      esac
  esac
}



typeset -A opt_args

if [[ $zsh_eval_context[-1] == eval ]]; then
  # eval/source/. command, register function for later
  compdef _shtab_gen_completion_py -N gen_completion.py
else
  # autoload from fpath, call function directly
  _shtab_gen_completion_py "$@"
fi
