from .core import (
    download_extension,
    search_extension,
    inspect_extension,
    get_extension_info,
    check_update,
    preview_extension,
    audit_extension,
    diff_extensions,
    analyze_risk,
    verify_signature,
    extract_extension,
    batch_download,
    scan_extension,
    generate_report,
    convert_extension,
    get_repo_stats,
    generate_unified_report,
    generate_html_report,
    share_report,
)

from .exceptions import (
    FetchextError,
    NetworkError,
    ConfigError,
    ExtensionError,
    SecurityError,
    IntegrityError,
    InsufficientDiskSpaceError,
    NotFoundError,
    AnalysisError,
)

from .constants import ExitCode

__all__ = [
    "download_extension",
    "search_extension",
    "inspect_extension",
    "get_extension_info",
    "check_update",
    "preview_extension",
    "audit_extension",
    "diff_extensions",
    "analyze_risk",
    "verify_signature",
    "extract_extension",
    "batch_download",
    "scan_extension",
    "generate_report",
    "convert_extension",
    "get_repo_stats",
    "generate_unified_report",
    "generate_html_report",
    "share_report",
    "FetchextError",
    "NetworkError",
    "ConfigError",
    "ExtensionError",
    "SecurityError",
    "IntegrityError",
    "InsufficientDiskSpaceError",
    "NotFoundError",
    "AnalysisError",
    "ExitCode",
]
